Development
fond-of/fond-of-spryker-google-tag-manager-store-connector pull request #6
Opened 2020-12-01 10:43 UTC by DerCalli

**Description:**

- replace multiple plugins by one plugin which extends datalayer with all properties
- remove old plugin
- adjust unit tests

2020-12-01 10:50 UTC, daniel-rose requested changes

2020-12-01 10:50 UTC, daniel-rose commented on src/FondOfSpryker/Yves/GoogleTagManagerStoreConnector/Expander/StoreDataLayerExpander.php
> +        Store $store,
Use the a bridge of store client for getting current store information. --> https://github.com/spryker/store/blob/f55682a4502ce8afceef2439924a82b820ebe1f6/src/Spryker/Client/Store/StoreClientInterface.php#L22

2020-12-01 10:50 UTC, daniel-rose commented on src/FondOfSpryker/Yves/GoogleTagManagerStoreConnector/Plugin/DataLayer/StoreDataLayerExpanderPlugin.php
> +    public function expand(string $page, array $twigVariableBag, array $variableList): array
Use $dataLayer instead of $variableList. It is a **DataLayer**ExpanderPluginInterface.

2020-12-02 09:11 UTC, julianzimmermann approved these changes

2020-12-02 09:17 UTC, daniel-rose requested changes

2020-12-02 09:17 UTC, daniel-rose commented on src/FondOfSpryker/Yves/GoogleTagManagerStoreConnector/Expander/StoreDataLayerExpander.php
> +class StoreDataLayerExpander implements StoreDataLayerExpanderInterface
StoreDataLayerExpander -> DataLayerExpander
StoreDataLayerExpanderInterface -> DataLayerExpanderInterface

2020-12-02 09:17 UTC, daniel-rose commented on src/FondOfSpryker/Yves/GoogleTagManagerStoreConnector/GoogleTagManagerStoreConnectorFactory.php
> +    public function createStoreDataLayerExpander(): StoreDataLayerExpanderInterface
createDataLayerExpander

2020-12-03 05:56 UTC, daniel-rose approved these changes

2021-01-11 12:51 UTC, merged